tap "homebrew/bundle"

# Shell and development tools
brew "actionlint"
brew "bun"
brew "diff-so-fancy"
brew "ffmpeg"
brew "fnm"
brew "gh"
brew "git"
brew "gitleaks"
brew "htop"
brew "pure"
brew "shellcheck"
brew "uv"
brew "wget"
brew "zsh"

# Everyday apps
cask "1password"
cask "1password-cli"
cask "arc"
cask "cleanshot"
cask "copilot-cli"
cask "figma"
cask "finicky"
cask "firefox"
cask "ghostty"
cask "google-chrome"
cask "obsidian"
cask "raycast"
cask "reflex-app"
cask "signal"
cask "spotify"
cask "vlc"

# Design tools and fonts
cask "font-fira-code"
cask "font-ibm-plex-mono"
cask "font-ibm-plex-sans"
cask "font-ibm-plex-serif"
cask "font-inter"
cask "font-league-gothic"
cask "font-source-sans-3"
cask "sim-daltonism"

# Quick Look
cask "qlmarkdown"
cask "syntax-highlight"
